In [83]:
import numpy as np
from math import factorial

In [84]:
def combinations(n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))

def arrangements(n, k):
    return int(factorial(n) / factorial(n - k))

def permutations(n):
    return int(factorial(n))

#### 1. Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Составьте закон распределения числа правильных ответов при простом угадывании. Найдите M(X), D(X).

In [85]:
# Число вопросов n = 5
# Вероятность правильно ответить на вопрос p = 1/4
# k принимает значения от 0 до n

In [86]:
n = 5
p = 1/4
q = 1 - p
probs = []
x_val = []
for k in range(0, n+1):
    P = combinations(n, k) * (p**k) * q**(n-k)
    probs.append(P)

In [87]:
probs

[0.2373046875,
 0.3955078125,
 0.263671875,
 0.087890625,
 0.0146484375,
 0.0009765625]

In [88]:
x_val = np.arange(0, n+1)
x_val

array([0, 1, 2, 3, 4, 5])

In [89]:
# первый способ
m = x_val.dot(probs)
m

1.25

In [90]:
# второй способ, так как для биномиально распределенной дискретной величины можно вычислить по формуле:M(X)=np
m = n*p
m

1.25

In [91]:
# аналогично для дисперсии
d = n*p*q
d

0.9375

In [92]:
y_val = x_val - m
y_val

array([-1.25, -0.25,  0.75,  1.75,  2.75,  3.75])

In [93]:
z_val = y_val ** 2
z_val

array([ 1.5625,  0.0625,  0.5625,  3.0625,  7.5625, 14.0625])

In [94]:
d = z_val.dot(probs)
d

0.9375

#### 2 Пользователь получает в среднем 10 писем со спамом на свой почтовый ящик за сутки. Найти число N, такое, что с вероятностью 0.95 пользователь получит не более N писем со спамом за текущий день.

In [95]:
def poisson_proba(k: int, lambda_: float) -> float:
    """Формула Пуассона.
    """    
    return (lambda_ ** k) * (np.exp(-lambda_)) / np.math.factorial(k)

$\lambda$ = 10 писем со спамом в сутки <br>
P(X<=N) = 0.95

In [ ]:
# В лоб перебираем вероятности получения от 0 до N писем, до тех пор пока вероятность получения N писем не стает равна ~0.95

In [129]:
lambda_ = 10
i = 0
p = 0
while True:
    p = sum(poisson_proba(k=y, lambda_=lambda_) for y in range(i))
    #print(p)
    if round(p, 2) == 0.95:
        break
    i = i + 1

In [127]:
print('Искомое число N равняется ', i)

Искомое число N равняется  16


#### 3. Производятся выстрелы по мишени. Вероятность попадания в мишень при одном выстреле равна 0.01. Сколько выстрелов нужно сделать чтобы быть уверенным с вероятностью 0.9, что хотя бы 6 раз будет совершено попадание?

$$P(k < 6) = P_n^0 + P_n^1 + ... P_n^5$$

Соответственно, складываем  вероятность для события, когда мы попали меньше 6 раз. Обратная ей вероятность будет описывать попадание 6 и больше раз, и она должна равняться 0.9. <br>

In [298]:
def bernulli(n, k, p, q):
    return combinations(n, k) * (p**k) * q**(n-k)

In [299]:
p = 0.01
q = 1 - p
n = 6 # шаги (выстрелы)
hits = 6 # хотя бы 6 попаданий

In [300]:
P1 = 0
while P1 <= 0.9: # внешний цикл работает, пока вероятность не станет заданной условием, т.е. 0.9
    P = 0
    for i in range(hits): # внутренний цикл считает полную вероятность по теореме сложения несовместных событий
        #print(bernulli(n, i, p, q))
        P += bernulli(n, i, p, q)   
    P1 = 1 - P
    n += 1  # не забыть в ответе отнять единицу


In [301]:
print(f'Требуется {n-1} выстрелов')

Требуется 926 выстрелов
